[package]
name = "runterra-of-legends-simulator"
version = "0.1.0"
authors = ["Eunchul Song <sech9446@naver.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lordeckcodes = { version = "0.3", features = [] }
